version: 0.1

#environment_variables:
#  plaintext:
#    key: "value"

phases:
  install:
    commands:
      - echo Install started on `date`
      - npm install -g yarn
      - yarn
  pre_build:
    commands:
      - echo Prebuild started on `date`
  build:
    commands:
      - echo Build started on `date`
      - yarn test
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - location
#    - location
#  discard-paths: yes